version: "3.3"
services:
  node:
    build: .
    restart: always
    ports:
      - "1234:80"
  proxy:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./dist/client:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - node
