npm uninstall --save body-parser
npm uninstall --save cache-manager
npm uninstall --save cache-manager-redis
npm uninstall --save cluster
npm uninstall --save connect-redis
npm uninstall --save cookie-parser
npm uninstall --save csurf
npm uninstall --save dayjs
npm uninstall --save express-session
npm uninstall --save extend
npm uninstall --save find
npm uninstall --save http-errors
npm uninstall --save mime-types
npm uninstall --save morgan
npm uninstall --save ms
npm uninstall --save node-uuid
npm uninstall --save pug
npm uninstall --save static-asset
npm uninstall --save url
npm uninstall --save winston
npm uninstall --save winston-debug
